// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:774cc786-d12d-409b-a18e-1c737499becd',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'exchangeapp-hosting-mobilehub-486449943',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1ei6efyglttix.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"exchangeapp-mobilehub-486449943-tasks","attributes":[{"name":"userId","type":"S"},{"name":"taskId","type":"S"},{"name":"category","type":"S"},{"name":"created","type":"N"},{"name":"description","type":"S"}],"indexes":[{"indexName":"DateSorted","hashKey":"userId","rangeKey":"created"}],"region":"us-west-2","hashKey":"userId","rangeKey":"taskId"},{"tableName":"exchangeapp-mobilehub-486449943-markets","attributes":[{"name":"marketId","type":"S"},{"name":"name","type":"S"},{"name":"ask","type":"S"},{"name":"bid","type":"S"},{"name":"change","type":"N"},{"name":"created","type":"N"},{"name":"high24hr","type":"S"},{"name":"icon","type":"S"},{"name":"isActive","type":"BOOL"},{"name":"lastPrice","type":"N"},{"name":"low24hr","type":"S"},{"name":"nameCode","type":"S"},{"name":"primaryCurrency","type":"S"},{"name":"secondaryCurrency","type":"S"},{"name":"spread","type":"S"},{"name":"volume","type":"N"}],"indexes":[{"indexName":"VolumeSorted","hashKey":"marketId","rangeKey":"volume"},{"indexName":"ChangeSorted","hashKey":"marketId","rangeKey":"change"}],"region":"us-west-2","hashKey":"marketId","rangeKey":"name"},{"tableName":"exchangeapp-mobilehub-486449943-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-west-2","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': '066adab8caa54b6c99379ca66aa1812f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '586fb998-15de-11e8-b983-1df4d428e0df',
    'aws_project_name': 'exchangeApp-2018-02-19-20-35-28',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'exchangeapp-mobilehub-486449943',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'exchangeapp-userfiles-mobilehub-486449943',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_ZEjpxxZD1',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '16o6rbh9s3vhh2egl82vvur52n',
}

export default awsmobile;
